### ISSUE TITLE
ClouMasking in python

### ISSUE THREAD

**Issue by luanschimidel** [SMByC/CloudMasking#1]
Hello, i would like know if there's a tutorial for te cloud masking funcionalities in the terminal of the pyqgis.

**Comment by XavierCLL** [comment]
Hi,
This plugin is only an interactive plugin (not possible to use it in the terminal or pyqgis), the idea of the plugin is process image by image and not in a bulk process: https://github.com/SMByC/CloudMasking#motivation

if you want masking in a bulk process I recommend use/implement this http://www.pythonfmask.org (but it is only fmask)

**Comment by XavierCLL** [comment]
I'm going to close this, any other comments/questions feel free to open it again o create a new one
