### ISSUE TITLE
Cloud Masking Not working

### ISSUE THREAD

**Issue by ahunanyamichael** [SMByC/CloudMasking#11]
'NoneType' object has no attribute 'name i need help

**Comment by XavierCLL** [comment]
Hi @ahunanyamichael 

Could you please describe your problem? what image are you trying to process? the error log, a screenshot, the info of your OS

**Comment by XavierCLL** [comment]
test the new version

**Comment by YSgonzalez** [comment]
No corre a la hora de generar la mascara, " No such file or directory" genera este error de exportación

**Comment by XavierCLL** [comment]
Hola @YSgonzalez estas usando la ultima version del plugin? tiene una captura de pantalla de exacta la opcion que te genera el error

**Comment by YSgonzalez** [comment]
Hola buenas tardes, si mira, en el presente correo te adjunto el error con
los plugins.
 [image: image.png]
[image: Captura de Pantalla 2022-05-26 a la(s) 1.55.19 p.m..png]

**Comment by XavierCLL** [comment]
@YSgonzalez algo paso y las imagenes que adjuntaste no se cargaron en tu comentario
