### ISSUE TITLE
CloudMasking Error

### ISSUE THREAD

**Issue by jpa09** [SMByC/CloudMasking#13]
![image](https://user-images.githubusercontent.com/122112598/211057067-2245d5e9-4dd2-473b-a3bc-e97436d105ba.png)

**Comment by XavierCLL** [comment]
Hi thanks for report it, this error was fixed, please use this zip https://github.com/SMByC/CloudMasking/issues/12#issuecomment-1336431695 meanwhile I push the new version

**Comment by XavierCLL** [comment]
Fixed in v23.1.7
