### ISSUE TITLE
Can't load plugin - classFactory()

### ISSUE THREAD

**Issue by apuzzi** [SMByC/CloudMasking#14]
I get this error when trying to install the plugin:

Couldn't load plugin 'CloudMasking' due to an error when calling its classFactory() method 

AttributeError: module 'CloudMasking' has no attribute 'classFactory' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
AttributeError: module 'CloudMasking' has no attribute 'classFactory'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.16.4-Hannover Hannover, 654e76b3cb 

Python Path:
C:\Users\apuzz\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\planet_explorer\extlibs
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
C:/Users/apuzz/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/apuzz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\Users\apuzz\AppData\Roaming\Python\Python37\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/apuzz/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\apuzz\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows
C:\Users\apuzz\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
C:\Users\apuzz\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\SentinelHub\external\oauthlib-3.1.0-py2.py3-none-any.whl
C:\Users\apuzz\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\SentinelHub\external\requests_oauthlib-1.3.0-py2.py3-none-any.whl
C:/Users/apuzz/Desktop/intro-rs-data

I saw the other issues about this but couldn't figure out why it is happening, I'm using Python 64 bits. Any clues?

**Comment by apuzzi** [comment]
I've uninstalled QGIS 3.16.4-Hannover and installed version 3.28 Firenze and was able to load the plugin.

**Comment by XavierCLL** [comment]
Hi @apuzzi exactly, I was going to write you that, the latest version of this plugin does not support old Qgis versions

**Comment by apuzzi** [comment]
thank you, Xavier!
