### ISSUE TITLE
Masking error

### ISSUE THREAD

**Issue by luthfanahmad** [SMByC/CloudMasking#4]
Hello, I'm masking my satellite image, and when it comes out, not everything is masked (in this case, the sea). I'm using MacOS Big Sur Version 11.1, and QGIS version 3.16.3. I have attached an example of a satellite image that failed to mask.

<img width="858" alt="Screen Shot 2021-01-29 at 20 30 48" src="https://user-images.githubusercontent.com/60228636/106281115-5d3c6e00-6271-11eb-953f-0a7c7deb6e54.png">
<img width="856" alt="Screen Shot 2021-01-29 at 20 31 04" src="https://user-images.githubusercontent.com/60228636/106281203-79d8a600-6271-11eb-8618-0434b6df9967.png">

**Comment by XavierCLL** [comment]
Hi, 
That is not literally an error of the plugin, remember that the fmask and other quality control layers aren't perfect, so combine it to have a better mask, for example in your case test combine the fmask with the Blue band (test it alone to see the best threshold) or masking the sea at the end of the process using land/country mask.
Bye

**Comment by XavierCLL** [comment]
@luthfanahmad I'll close the issue, if you have more questions/comments/ideas just do it or reopen the issue
