### ISSUE TITLE
Couldn't load plugin

### ISSUE THREAD

**Issue by ghost** [SMByC/CloudMasking#7]
**I have a problem loading the Plugin, I am using Ubuntu Xfce 4.12 and I get the following error:**

```

Couldn't load plugin 'CloudMasking' due to an error when calling its classFactory() method 

ImportError: dynamic module does not define module export function (PyInit__fillminima) 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/itadmin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/CloudMasking/__init__.py", line 102, in classFactory
    from .cloud_masking import CloudMasking
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/itadmin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/CloudMasking/cloud_masking.py", line 40, in 
    from CloudMasking.core import cloud_filters, color_stack
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/itadmin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/CloudMasking/core/cloud_filters.py", line 44, in 
    from fmask import fmask, landsatTOA, landsatangles, config, saturationcheck
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/itadmin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/CloudMasking/libs/fmask/fmask.py", line 70, in 
    from . import fillminima
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/itadmin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/CloudMasking/libs/fmask/fillminima.py", line 35, in 
    from CloudMasking.libs.fmask import _fillminima
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: dynamic module does not define module export function (PyInit__fillminima)
```

Python version: 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0] 
QGIS version: 3.16.3-Hannover Hannover, 94ac9f21b8 

Python Path:
/usr/share/qgis/python
/home/itadmin/.local/share/QGIS/QGIS3/profiles/default/python
/home/itadmin/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/itadmin/.local/share/QGIS/QGIS3/profiles/default/python
/home/itadmin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/vrtbuilderplugin
/home/itadmin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/vrtbuilderplugin/vrtbuilder

```
Please help

**Comment by leonharol** [comment]
También hablo español para mas facilidad

**Comment by XavierCLL** [comment]
Que mas parcero, el cloudmasking usa una librerias compilas para correr el fmask, el paquete por lo general viene con todas pero principalmente para 64bit, es tu sistema de 32bit? ejecuta `uname -a` para saber

**Comment by ghost** [comment]
Si mira me salió esto:

`Linux analytics 5.4.0-1043-azure #45~18.04.1-Ubuntu SMP Sat Mar 20 16:16:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

La verdad creo que es algo de las librerías de Python y el cómo está instalado, pero llevo todo el día tratando de solucionar ese chicharrón y me tiene varado ahí. Si me pudieras ayudar seria de gran ayuda amigo, eres muy amable!

**Comment by XavierCLL** [comment]
Pueden ser que sea, o por la version de python o la de Qgis, que ambas son algo viejitas, pero no importa, te voy a dar algunas instrucciones que creo que con eso se soluciona, es compilando las librerias y en linux se facilita esa tarea:

1)
entra a esta ruta `/home/itadmin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/CloudMasking/libs/fmask`
borra los archivos terminados en `.so`

2)
en esa misma ruta entra a una carpeta `libs` abre la terminal ahi y ejecuta: `python3 setup.py build_ext`

3)
dentro de la carpeta `build` que creo en el paso anterior copia los archivos `.so` borrados en el primer paso y copialos en la ruta que los borro del paso 1

Cierra Qgis y vuelvelo a abrir, espero que con eso sirva, me cuentas
Saludos

**Comment by leonharol** [comment]
¡Que grande eres! Funcionó a la perfección, se cargó y ejecutó el Plugin como debería ser. Muchas pero muchísimas gracias amigo por tu tiempo, ayuda y pronta respuesta! En serio que tu Plugin es lo mas top que hay en QGis! Muchas gracias nuevamente, que desvarada que me pegaste. Saludos! 👍

**Comment by XavierCLL** [comment]
Que bien que te funciono! un placer ayudarte Harold. Saludos!
