### ISSUE TITLE
Plugin causing issue with raster properties function

### ISSUE THREAD

**Issue by cavrinceanu** [SMByC/CloudMasking#8]
Hi! I've recently had issues with accessing the raster properties and determined that it was a 3rd party plugin that was interfering with the core function. After removing one by one, Cloud masking seems to be the issue. Can you please check?

**Comment by XavierCLL** [comment]
Hi,
Thanks for the report! 
How do you accessing to the raster properties? with which tool? what is the error? could you share with me the error text or screenshot of it? thanks

**Comment by XavierCLL** [comment]
Closed, not much info provided, open it again if you can add more info for debugging, thanks
