### ISSUE TITLE
Install Error on 3.16 QGIS

### ISSUE THREAD

**Issue by domierosina** [SMByC/CloudMasking#9]
I had this plugin running about a week ago. I did an update to my QGIS, realized that the plugin did not work with 3.20 and reverted back to the long term version, 3.16. I am still getting the same error. 

`Couldn't load plugin 'CloudMasking' due to an error when calling its classFactory() method `

The file it keeps getting confused with (I have tried on two separate systems now) is this one: 
`/CloudMasking/libs/fmask/_fillminima.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00 `

There seems to be an import error. I have tried installing via ZIP file and through the plugin library in QGIS.

**Comment by XavierCLL** [comment]
Hi @domierosina, that problem is related to binary libraries inside the plugin

Could you tell me which is your OS? 64 or 32bits? 

you could also open the python console in Qgis and execute `sys.version_info`

**Comment by domierosina** [comment]
The MAC OS is 10.15.7. I am also running on Windows 10, 64 bit. 
Both are: Maj 3, Min 9 and micro 6.

**Comment by XavierCLL** [comment]
Thanks, I realized that the binary library that the plugin use internally is only for python 3.6 and 3.7 for those OSs, I'll update with the latest python version, today or tomorrow I'll send an update to test it.

**Comment by domierosina** [comment]
Thank you so much! Very much appreciated. :)

**Comment by XavierCLL** [comment]
I've uploaded to the Qgis repository the new version 21.7.15 fixing that problem, thanks for reporting it!
